spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reservation?characterEncoding=UTF-8
    username: root
    password: zerobase

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  jwt:
    secret: Z3l1cmktcmVzZXJ2YXRpb24tcHJvamVjdC1zZWNyZXQta2V5