spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reservation?characterEncoding=UTF-8
    username: root
    password: imgyuri0517

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

  jwt:
    secret: Z3l1cmktcmVzZXJ2YXRpb24tcHJvamVjdC1zZWNyZXQta2V5

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher